### ISSUE TITLE
A few Questions about repository

### ISSUE THREAD

**Issue by jmalak** [sezero/watt32#1]
Hi,
I have a few questions only.

- I am not sure if it is intentional, but default branch in this repository is `2.2.10-sezero` branch.
It is a little confusing for me, I expected usuall `master` branch.
- What is relation to [Gisle Vanen repository](https://github.com/gvanem/Watt-32) , I would like to submit some Watcom fixes that I am not sure to which repository it is better

**Comment by sezero** [comment]
>  I am not sure if it is intentional, but default branch in this repository is `2.2.10-sezero` branch.
>  It is a little confusing for me, I expected usuall `master` branch.

It is intentional. I usually use 2.2.10+fixes+some improvements in my code, that's why it's my default branch.

>  What is relation to [Gisle Vanen repository](https://github.com/gvanem/Watt-32)

@gvanem did not originally have a git repo (or any repo) of watt32, so I generated one on my own, and he later forked it for mainstream development.
